add a 'flags' subcommand to list global flags
wal-g/wal-g pull request #1033
Opened 2021-07-06 16:07 UTC by LeGEC

### Database name
I work with PostgreSQL, right now I only added this `flags` subcommand to `main/pg`

# Pull request description
in `main/pg` binary :

add a 'flags' subcommand to list global flags

additionally :
* remove this list from the default list of options,
* change default doc template to mention :
    "list available flags with 'wal-g flags'"

fixes #1032 (for main/pg)

2021-08-18 11:24 UTC, usernamedt commented
Hi!

This is a cool idea. The amount of auto-generated flags is definitely overwhelming.  

Currently, when I run the `wal-g flags` command with no configuration, I get the following error:
```
➜  pg git:(1032-pg-help-flags) ./wal-g flags                                                                                                                                                                   
ERROR: 2021/08/18 16:15:03.156199 Failed to find any configured storage
```

I guess that this command should not depend on any configuration parameters, but simply output the available flags.

This happens because of the AssertRequiredSettingsSet() call in the PersistentPreRun of the `pg` command. Maybe there is another way to add the `flags` subcommand?

2021-08-18 12:04 UTC, usernamedt requested changes
needs changes

2021-11-16 12:57 UTC, usernamedt approved these changes

2021-11-16 12:58 UTC, usernamedt commented on cmd/pg/flags.go
> +// flagsCmd represents the delete command
```suggestion
// flagsCmd represents the flags command
```

2021-11-16 15:54 UTC, usernamedt commented
Command itself looks good, but I think that `flags` should be a global subcommand for any database. Can you move it to a separate package? You can use [storage tools global subcommand](https://github.com/wal-g/wal-g/blob/master/cmd/st/st.go) as a reference.

2021-11-17 15:16 UTC, usernamedt commented
I moved the flags subcommand and all common cmd init logic to the `common`. Now it should work fine for all databases.

2021-11-18 20:11 UTC, mialinx approved these changes
LGTM

2021-11-19 14:07 UTC, perekalov approved these changes

2021-11-19 15:20 UTC, merged