MySQL > Check binlog GTIDs before pushing binlogs to S3
wal-g/wal-g pull request #1085
Opened 2021-09-08 08:10 UTC by ostinru

* Add `wal-g binlog-list` for MySQL - this command extracts real GTID Sets from local binlogs.
 * Add `--check-gtids` to `wal-g binlog-push` for MySQL.
   When this flag is specified, wal-g will extract executed_gtid_set from all binlogs,
   and will upload binlogs with new transactions. As a result some space will be saved in S3.
   In addition PITR on time that happend just after failover will be faster (fewer binlogs to apply)

Note: It is Proof-of-concept! Don't use it in production. In theory we can lose some binlogs because
   in this proposal we are using executed_gtid_set instead of real binlog GTID Set.

2021-09-17 15:27 UTC, mialinx requested changes

2021-09-23 15:35 UTC, ostinru commented on internal/databases/mysql/binlog_push_handler.go
> +	err := parser.ParseFile(filename, 0, func(event *replication.BinlogEvent) error {
I think that it could be user's responsibility to use `--check-gtids` flag or not

2021-09-23 15:45 UTC, ostinru commented on internal/databases/mysql/binlog_push_handler.go
> +			err := previousGTID.Decode(event.RawData[19:])
I believe you wanted to point to `BinlogParser.Parse(data []byte)`[1].
However I prefer this offset magic to runtime type casting.

[1] https://github.com/go-mysql-org/go-mysql/blob/1629d9bf044a5dcce91810dc9240cc97c0f3aaf9/replication/parser.go#L318

2021-10-05 08:33 UTC, mialinx approved these changes

2021-10-05 11:59 UTC, merged