Add pgbackrest wal-fetch and wal-show commands
wal-g/wal-g pull request #1202
Opened 2022-01-24 16:15 UTC by Dm17r1y

Write command, that works with pgbackrest wal files ([continue adding pgbackrest backup restore feature](https://github.com/wal-g/wal-g/pull/1139))

Use `wal-g pgbackrest wal-show` command to show current pgbackrest wal files
Use `wal-g pgbackrest wal-fetch` command to fetch wal file from pgbackrest backup

2022-01-24 17:48 UTC, serprex commented on internal/fetch_helper.go
> +	reader, exists, err := TryDownloadFile(folder, fileName)
What's the purpose of this?

It seems like no compression should be the last resort

2022-01-25 07:22 UTC, usernamedt requested changes

2022-01-25 07:22 UTC, usernamedt commented on docker/pg_tests/scripts/tests/pgbackrest_backup_fetch_test.sh
>  /usr/lib/postgresql/10/bin/pg_ctl -D ${PGDATA} -w stop
Let's do an online backup just like it is done in the wal-g backup-fetch test since we support the `wal-fetch` now.

2022-01-28 07:11 UTC, usernamedt commented on docker/pg_tests/scripts/tests/pgbackrest_backup_fetch_test.sh
> +pgbench -c 2 -T 100000000 -S &
I suggest to use the `pgbench -c 2 -T 1000 &` since the select-only workload doesn't test anything.

2022-05-20 05:54 UTC, usernamedt approved these changes

2022-05-20 05:55 UTC, merged