[WIP] Move methods with uploading directories to common namespace
wal-g/wal-g pull request #1237
Opened 2022-03-20 16:08 UTC by hariton27sy

### Database name
Common work

# Pull request description

### Describe what this PR fix
Problem is that methods for uploading direactories are postgres-specific. Methods are moved to common package in this PR

2022-03-20 21:20 UTC, serprex commented on go.mod
> +require github.com/google/brotli/go/cbrotli v0.0.0-20220110100810-f4153a09f87c
Clean up dependency shuffling

2022-03-20 21:20 UTC, serprex commented on internal/parallel/tar_file_sets.go
> +// DONE
DONE?

2022-03-21 18:30 UTC, hariton27sy commented on internal/databases/postgres/tar_ball_file_packer.go
>  type TarBallFilePacker struct {
There is an interface with name TarBallFilePacker, but i forget to rename this implementation to something like `PostgressTarBallPacker`

2022-03-23 07:55 UTC, usernamedt requested changes

2022-03-23 07:55 UTC, usernamedt commented on internal/parallel/tar_ball_file_packer.go
> +	if p.options.verifyPageChecksums {
You can remove the checksum verification since it is Postgres-related feature.

2022-05-14 14:29 UTC, usernamedt requested changes

2022-05-14 14:29 UTC, usernamedt commented on internal/parallel/directory_loader.go
> +type DirectoryLoader interface {
`DirectoryDownloader`?

2022-05-14 14:29 UTC, usernamedt commented on internal/parallel/directory_uploader.go
> +type DirectoryUploader interface {
`DirectoryUploader`

2022-05-14 14:29 UTC, usernamedt commented on internal/parallel/tar_ball_file_packer.go
> +	errorGroup, _ := errgroup.WithContext(context.Background())
Since there is only one goroutine left, `errorGroup` is no longer needed. You can remove the `errorGroup` and goroutine completely.

2022-05-14 14:29 UTC, usernamedt commented on internal/databases/postgres/bundle.go
>  	Directory string
We can embed the new `Bundle` struct here.

2022-05-14 14:29 UTC, usernamedt commented on internal/parallel/budle_files.go
> +package parallel
s/budle_files.go/bundle_files.go/

2022-05-14 14:30 UTC, usernamedt commented
Also, the `parallel` package name is too abstract. I suggest either renaming or moving its contents to the `internal` package.

2022-05-26 07:02 UTC, usernamedt approved these changes

2022-05-26 07:02 UTC, merged