Reformat LSN output
wal-g/wal-g pull request #1259
Opened 2022-04-23 07:54 UTC by beklenishchevS

### PostgreSQL

# Pull request description

### Describe what this PR fix
Problem is unconventional LSN format in wal-g output https://github.com/wal-g/wal-g/issues/987. 

### Please provide steps to reproduce (if it's a bug)
// it can really help

### Please add config and wal-g stdout/stderr logs for debug purpose

also you can use WALG_LOG_LEVEL=DEVEL for logs collecting
<details><summary>If you can, provide logs</summary>
<p>
```bash
any logs here
```
</p>
</details>

2022-04-25 08:59 UTC, usernamedt requested changes

2022-04-25 08:59 UTC, usernamedt commented on internal/databases/postgres/wal_show_output_writer.go
> +		row := table.Row{tl.ID, tl.ParentID, ConvertLSNtoPostgresFormat(tl.SwitchPointLsn), tl.StartSegment,
Actually, you can utilize the `pgx.FormatLSN` function that does exactly this job.

2022-04-25 09:04 UTC, usernamedt commented
I suggest changing the output format in other places too. For example, here:
- https://github.com/wal-g/wal-g/blob/200e8c01a7595a04e86484ca5eb6a90235d69cf3/internal/databases/postgres/backup_list_handler.go
- https://github.com/wal-g/wal-g/blob/12ce95bbd4f9349449003aac817b036c8deb7966/internal/databases/postgres/backup_push_handler.go#L31
- https://github.com/wal-g/wal-g/blob/12ce95bbd4f9349449003aac817b036c8deb7966/internal/databases/postgres/backup_push_handler.go#L181
- https://github.com/wal-g/wal-g/blob/12ce95bbd4f9349449003aac817b036c8deb7966/internal/databases/postgres/backup_push_handler.go#L189

2022-05-08 16:55 UTC, usernamedt commented
I've refactored this PR a little bit. Instead of formatting LSN in each place independently, I suggest introducing the custom `LSN` type with its own `Stringer` interface implementation.

2022-05-11 08:54 UTC, x4m approved these changes

2022-05-11 09:03 UTC, usernamedt approved these changes

2022-05-11 09:04 UTC, merged