Fix some wordings in docs
wal-g/wal-g pull request #1289
Opened 2022-06-09 16:42 UTC by x4m

### Database name
Wal-g provides support for many databases, please write down name of database you uses.

# Pull request description

### Describe what this PR fix
// problem is ...

### Please provide steps to reproduce (if it's a bug)
// it can really help

### Please add config and wal-g stdout/stderr logs for debug purpose

also you can use WALG_LOG_LEVEL=DEVEL for logs collecting
<details><summary>If you can, provide logs</summary>
<p>
```bash
any logs here
```
</p>
</details>

2022-06-09 16:52 UTC, OrangeDog requested changes

2022-06-09 17:01 UTC, x4m commented on docs/PostgreSQL.md
>  wal-g backup-push /backup/directory/path
I think it will not be obvious to users.
maybe wal-g backup-push /var/lib/postgresql/10/data ?

2022-06-09 17:15 UTC, OrangeDog commented on docs/PostgreSQL.md
>  wal-g backup-push /backup/directory/path
It should be obvious to postgres admins (the target audience). The default PGDATA path depends on distribution and version.

2022-06-13 16:35 UTC, x4m commented
@OrangeDog can you please take a look into updated PR?

2022-06-13 18:38 UTC, OrangeDog approved these changes

2022-06-14 08:09 UTC, reshke approved these changes

2022-06-14 08:09 UTC, merged

2022-06-16 13:51 UTC, OrangeDog commented on docs/PostgreSQL.md
> + If the PGDATA section is setted, WAL-G will check that command argument, environment variable PGDATA and config setting PGDATA are the same.
@x4m Turns out this wasn't correct. What it actually does is connect to the postgres server (via `PGHOST`) and ask what the data directory is. If it doesn't match the arg then it fails,

2022-06-16 14:47 UTC, x4m commented on docs/PostgreSQL.md
> + If the PGDATA section is setted, WAL-G will check that command argument, environment variable PGDATA and config setting PGDATA are the same.
Uhm, yes, it seems like we got a lot of safety checks here and there… feel free to sharpen docs as needed.