Less scary logging of absent metadata (e.g. for WAL-E backups)
wal-g/wal-g pull request #1292
Opened 2022-06-11 12:55 UTC by x4m

Fix for #1291

2022-06-11 20:39 UTC, usernamedt approved these changes

2022-06-13 18:54 UTC, usernamedt requested changes

2022-06-13 18:54 UTC, usernamedt commented on internal/delete_util.go
> +func PrintMetadataNotFoundError(backupTime BackupTime, err error) {
well, now this function not only prints but exits in case of non-404s so I guess it needs to be renamed

2022-06-15 08:14 UTC, teem0n approved these changes

2022-06-15 09:03 UTC, usernamedt approved these changes

2022-06-15 09:04 UTC, merged