Implement max file size for mysql
wal-g/wal-g pull request #1374
Opened 2022-11-08 09:09 UTC by bularond

Add config WALG_STREAM_SPLITTER_BLOCK_SIZE witch set maximum one file size for backup

2022-11-08 09:56 UTC, ostinru commented
@bularond , could you please elaborate on why do you want to limit file sizes? If I remember correctly, current implementation shouldn't keep whole files locally, so it is unclear what you are trying to improve here.

2022-11-14 09:22 UTC, mialinx commented
> @bularond , could you please elaborate on why do you want to limit file sizes? If I remember correctly, current implementation shouldn't keep whole files locally, so it is unclear what you are trying to improve here.

Main idea behind `max size` is to avoid uploading / downloading huge files, as it consumes a lot of memory (s3client multipart specific)

2022-11-14 10:12 UTC, mialinx requested changes
redesign needed

2022-11-14 10:12 UTC, mialinx commented on internal/stream_push_helper.go
> +			filesReaders := splitmerge.SplitMaxSizeReader(reader, uploader.blockSize, uploader.maxFileSize)
Does all the `fileReaders` read from `reader` at the same time ?

2022-11-14 10:12 UTC, mialinx commented on internal/splitmerge/splitmaxsizereader.go
> +	go func() {
why do we need a separate goroutine here ?

2022-11-15 08:07 UTC, ostinru commented
FYI: we have PR that limits size of files for single-stream backups: https://github.com/wal-g/wal-g/pull/1013 (PR weirdly named).

2022-11-17 09:20 UTC, ostinru commented on docker/mysql_tests/scripts/base_tests/splited_file_stream.sh
> +export WALE_S3_PREFIX=s3://mysqlfullxtrabackupbucket
Let's use a separate bucket for each test.
Don't forget to create it in `docker-compose.yml`

2022-11-18 13:55 UTC, mialinx commented
> FYI: we have PR that limits size of files for single-stream backups: #1013 (PR weirdly named).

Yes, but... it does not support split/merge parallel processing.  And it stores redundant info (Filenames) in sentinel.

2022-11-18 15:29 UTC, mialinx requested changes

2022-11-18 15:29 UTC, mialinx commented on internal/stream_metadata.go
> +	case LimitedFileSizeBackup:
It looks like thees two cases differ only in the last argument. May be join them together ?  And get rid of temporary  `limitedFileSize` variable

2022-11-18 15:29 UTC, mialinx commented on internal/stream_fetch_helper.go
> +func downloadFile(backup Backup, decompressor compression.Decompressor, fileName string, writer io.WriteCloser) error {
We have added 4 extra functions.

May we just modify `detectPartitionsCount` to return `[]int` (number of part for each partition).
And add one loop (over parts) in `DownloadAndDecompressSplittedStream` ?

2022-11-28 11:35 UTC, mialinx requested changes

2022-11-28 13:00 UTC, mialinx approved these changes
LGTM

2022-11-28 14:44 UTC, merged