enable using aws iam roles
wal-g/wal-g pull request #1377
Opened 2022-11-11 14:03 UTC by Qwiz

### Database name
All of them

## Pull request description
This PR allows using AWS IAM roles for S3 access. 
To do this, you need to set AWS_ROLE_ARN and AWS_ROLE_SESSION_NAME variables along with AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY.

### Describe what this PR fix
Currently, wal-g does not work with AWS IAM roles - you have to generate session token and pass it to wal-g env.
This PR adds ability to wal-g to get this token independently

2022-11-12 08:40 UTC, usernamedt commented
Looks OK, can you also add some information to the docs?

2022-11-12 08:40 UTC, usernamedt requested changes
Looks OK, can you also add some information to the docs?

2022-11-15 05:31 UTC, Qwiz commented
I changed docs as requested. Can you look at it?
And also can you make a prerelease binary of wal-g?

2022-11-16 11:47 UTC, usernamedt commented
LGTM

2022-11-16 11:47 UTC, usernamedt approved these changes
Looks good

2022-11-16 11:47 UTC, merged

2022-11-16 11:49 UTC, usernamedt commented
> I changed docs as requested. Can you look at it?
> And also can you make a prerelease binary of wal-g?

Sure