Add restore-point-list command for gp
wal-g/wal-g pull request #1397
Opened 2022-12-08 18:28 UTC by rogaliiik

Greenplum

Add restore-point-list command for Greenplum

2022-12-08 18:32 UTC, rogaliiik commented
The functionality of this command is very similar to "backup-list" command. Should i write unittests for these functions?

2022-12-09 10:57 UTC, usernamedt requested changes

2022-12-09 10:57 UTC, usernamedt commented on utility/utility.go
> +	return strings.Split(pathValue, "_restore_point")[0]
use the `RestorePointSuffix` constant

2022-12-09 10:57 UTC, usernamedt commented on internal/restore_point_list_handler.go
> +package internal
Restore point logic is greenplum-specific and should belong to the `internal/databases/greenplum`.

2022-12-09 10:57 UTC, usernamedt commented on cmd/gp/restore_point_list.go
> +	restorePointListCmd = &cobra.Command{
Add the corresponging notes to the documentation.

2022-12-09 10:57 UTC, usernamedt commented on utility/utility.go
>  	StreamMetadataFileName = "stream_metadata.json"
Same, this logic is greenplum-specific.

2022-12-09 10:59 UTC, usernamedt commented
> The functionality of this command is very similar to "backup-list" command. Should i write unittests for these functions?

A couple of unit test that checks that command works as expected will be enough

2022-12-20 11:14 UTC, usernamedt approved these changes

2022-12-20 11:15 UTC, merged