Implementation of the new binlog-server command
wal-g/wal-g pull request #1408
Opened 2022-12-29 13:04 UTC by Fizic

### Database name
mysql

# Pull request description

wal-g runs MySQL implementation, and when a slave is connected to it, downloads binlogs from the repository and gives them over the replication protocol.

Currently requires the use of the library version provided in this pull-request: https://github.com/go-mysql-org/go-mysql/pull/759

2023-01-01 13:53 UTC, lance6716 commented
Seems you can use go mod replace to let go-mysql use https://github.com/go-mysql-org/go-mysql/pull/759 and let the CI work :)

2023-01-06 06:44 UTC, ostinru commented
Wow! Great beginning!
I thought about this approach after reading ‘MySQL PiTR like a rockstar’[1][2][3] by @lefred
Below is my RFC I did some time ago, I hope you will find bits of it useful.

---
## Proposal [stage 1]

add new command `wal-g binlog-server`  that

- start listening a port
- parse requests on incoming connections (basic auth?)
- send *all* binlogs since backup timestamp (like we are doing it now) (known bug: https://github.com/wal-g/wal-g/issues/1386)
- be able to stop sending events when reaching point in time

**Open questions/discussion:**

1. we should parse binlogs to find PiT. Is it fast to parse binlogs in golang? (anyway, mysqlbinlog also parses binlogs)
2. at first glance `github.com/go-mysql-org/go-mysql` lacks ready-to-use code for server message parsing

## Proposal [stage 2]

This stage aims to make binlog-server generic: unlink it from backup_name.

for `wal-g binlog-push` - we should save GTID Sets to binlog sentinel, so `binlog-server` will be able to find the first binlog to serve

- Q: is there a chance for race between instances of wal-g writing the sentinel file?

for `wal-g binlog-server` we should be able to parse mysqld's [COM_BINLOG_DUMP_GTID](https://github.com/mysql/mysql-server/blob/mysql-cluster-8.0.30/sql/rpl_source.cc#L936
) request (get GTIDSet from it) and find a set of binlog files to be sent to `mysqld`



**Open questions/discussion:**

1. Should we add ‘test’ command that will check that we have information about all required binlogs (to allow users to fallback to the old approach if we are not sure)

# Other considerations

1. We should replay the first binlog from exact position: https://github.com/wal-g/wal-g/issues/1386

---

### Links
[1] https://lefred.be/content/howto-make-mysql-point-in-time-recovery-faster/
[2] https://www.slideshare.net/lefred.descamps/fosdem-mysql-friends-devroomffebruary-2018-mysql-pointintime-recovery-like-a-rockstar
[3] https://www.youtube.com/watch?v=PinKYCfv1MM&t=1787s

2023-01-09 11:57 UTC, teem0n commented on go.mod
> +	github.com/siddontang/go-log v0.0.0-20190221022429-1e957dd83bed
It seems that we don't need one more log. Let's remove this one

2023-01-09 11:57 UTC, teem0n commented on internal/databases/mysql/mysql.go
> +			if errors.Is(err, afero.ErrFileExists) {
Let's replace with `os.IsExist(err)`

2023-01-24 09:45 UTC, teem0n requested changes

2023-01-24 09:45 UTC, teem0n commented on internal/databases/mysql/binlog_server_handler.go
> +	rotateBinlogEvent.RawData = make([]byte, 4+1+4+4+4+2+8)
This magic number should be placed in const var with some description and links in comment : )

2023-01-24 09:45 UTC, teem0n commented on internal/config.go
> +	MysqlBinlogGetExecutedGTIDCmd = "WALG_MYSQL_BINLOG_GET_EXECUTED_GTID_COMMAND"
This command needs description in .md file with example (like WALG_MYSQL_BINLOG_REPLAY_COMMAND)

2023-01-24 09:45 UTC, teem0n commented on internal/databases/mysql/binlog_server_handler.go
> +		cmd, err := internal.GetCommandSetting(internal.MysqlBinlogGetExecutedGTIDCmd)
May be we can use getMySQLGTIDExecuted here?

2023-01-24 09:45 UTC, teem0n commented on internal/databases/mysql/binlog_server_handler.go
> +		if strings.Contains(executedGTIDSet, lastSentGTID) {
lastSentGTID should be read under some kind of lock, like sync.Mutex
Also, we can not use string.Contains here, we should parse lastSentGTID with gomysql.ParseGTIDSet

2023-01-24 09:45 UTC, teem0n commented on internal/databases/mysql/binlog_server_handler.go
> +			lastSentGTID = u.String() + ":1-" + strconv.Itoa(int(e.Event.(*replication.GTIDEvent).GNO))
Does we need "1-" here?
Can we just send SID:GNO here?

2023-01-24 09:45 UTC, teem0n commented on internal/databases/mysql/binlog_server_handler.go
> +		ok := s.AddErrorToStreamer(err)
Let's put this logic in method like "HandleEventError"

2023-01-24 09:45 UTC, teem0n commented on internal/databases/mysql/binlog_server_handler.go
> +		resultSet, _ := mysql.BuildSimpleTextResultset([]string{"SERVER_UUID"}, [][]interface{}{{"123"}})
123 should be read from config

2023-01-24 09:45 UTC, teem0n commented on internal/databases/mysql/binlog_server_handler.go
> +		resultSet, _ := mysql.BuildSimpleTextResultset([]string{"SERVER_ID"}, [][]interface{}{{"10000"}})
10000 should be read from config

2023-01-24 09:45 UTC, teem0n commented on internal/databases/mysql/binlog_server_handler.go
> +	binary.LittleEndian.PutUint32(rotateBinlogEvent.RawData[binlogEventPos:], 10000)
10000 should be read from config

2023-01-30 07:30 UTC, teem0n requested changes

2023-01-30 07:30 UTC, teem0n commented on cmd/mysql/binlog_server.go
> +var UntilTS string
We should not export this

2023-01-30 07:30 UTC, teem0n commented on internal/databases/mysql/binlog_server_handler.go
> +func HandleEventError(err error, s *replication.BinlogStreamer) {
We should not export this

2023-01-30 07:30 UTC, teem0n commented on internal/databases/mysql/binlog_server_handler.go
> +	rotateBinlogEvent := replication.BinlogEvent{}
Please add link to event format specs

2023-01-30 08:11 UTC, teem0n commented on internal/databases/mysql/mysql.go
> +			}
Let's hide error handling logic, like HandleEventError in binlog_server_handler.go

2023-02-03 08:26 UTC, teem0n approved these changes

2023-02-06 15:36 UTC, merged