Partial fetch
wal-g/wal-g pull request #1434
Opened 2023-02-20 11:50 UTC by Catmoonlight

### Database name
Wal-g provides support for many databases, please write down name of database you uses.

# Pull request description

### Describe what this PR fix
// problem is ...

### Please provide steps to reproduce (if it's a bug)
// it can really help

### Please add config and wal-g stdout/stderr logs for debug purpose

also you can use WALG_LOG_LEVEL=DEVEL for logs collecting
<details><summary>If you can, provide logs</summary>
<p>
```bash
any logs here
```
</p>
</details>

2023-02-20 19:13 UTC, usernamedt requested changes

2023-02-21 06:46 UTC, reshke commented on internal/databases/postgres/dir_database_tar_ball_composer.go
> +		d.fileDirCollection[path.Dir(info.Path)] = append(d.fileDirCollection[path.Dir(info.Path)], info)
By the way, Is tablespace support working well anywhere else in wal-g? 
Agreed about some warm messages. Supporting only base tablespace in first place is like TODO so future better us....

2023-02-27 14:30 UTC, reshke commented on internal/databases/postgres/backup_fetch_handler_new.go
> +		// directory must be empty before starting
Is this change intentional?

2023-03-06 10:33 UTC, usernamedt requested changes

2023-03-06 10:33 UTC, usernamedt commented on docker/pg_tests/scripts/tests/partial_backup_test.sh
> +if psql -t -c "select data from tbl1;" -d first -A | grep -q "$(printf '1\n2\n5\n6')"; then
Add test that reading from the `tbl2` fails?

2023-03-18 08:21 UTC, usernamedt approved these changes

2023-03-18 08:22 UTC, merged