add tests to LSN Regex
wal-g/wal-g pull request #1462
Opened 2023-04-26 12:50 UTC by IvanSibirtsev

### Database name
Postgres

# Pull request description

Added tests for utility.RegexpLSN

2023-04-26 14:12 UTC, serprex approved these changes

2023-04-26 14:13 UTC, serprex commented on utility/utility_test.go
> +		expectedLen int
```suggestion
```
No need for `expectedLen` when `expected` already has that information

2023-04-26 14:59 UTC, IvanSibirtsev commented on utility/utility.go
> +var RegexpLSN = regexp.MustCompile(patternLSN)
Because I need to use it in file with tests

2023-05-02 15:50 UTC, usernamedt requested changes

2023-05-02 15:50 UTC, usernamedt commented on utility/utility_test.go
> +func GetRandomizedString(length int) string {
GetRandomizedHexString

2023-05-03 14:08 UTC, usernamedt approved these changes

2023-05-03 15:28 UTC, merged