Add prefetch prefix for wal-prefetch cmd
wal-g/wal-g pull request #1471
Opened 2023-05-10 05:32 UTC by denisSurkov

> This is duplicate from https://github.com/wal-g/wal-g/pull/1470 because that PR was broken

### Database name
any

# Pull request description
`ERROR` logs from prefetch are often misleading. Original issue: https://github.com/wal-g/wal-g/issues/1328

### Describe what this PR fix
Adding `PREFETCH` prefix for all loggers to `wal-preferch` command. I am not sure that the prefix would solve issue. But it would definitely help to separate internal tool from real `wal fetch` command.

### Please provide steps to reproduce (if it's a bug)
Run `pg_full_backup_without_files_metadata_test` test.

2023-05-10 05:34 UTC, denisSurkov commented
@usernamedt , can you review again please? 

Yesterday github had an incident, so previous PR was broken.

2023-05-10 12:29 UTC, usernamedt requested changes

2023-05-11 08:52 UTC, usernamedt approved these changes

2023-05-12 06:23 UTC, denisSurkov commented
@usernamedt , did you forget to merge it or you have "merge queue"?

2023-05-14 13:14 UTC, merged