Now supported: additional headers for s3 requests
wal-g/wal-g pull request #1535
Opened 2023-08-24 08:00 UTC by debebantur

### Database name
postgres

# Pull request description
Added headers to s3 requests

2023-08-24 08:11 UTC, x4m requested changes

2023-08-24 08:11 UTC, x4m commented on pkg/storages/s3/session.go
> +func getHeaders(encodedHeaders string) (map[interface{}]interface{}, error) {
HTTP header keys and values known to be strings. I do not see a point for interface{} thing.

2023-08-24 08:11 UTC, x4m commented on pkg/storages/s3/session.go
> +func refomHeaderListToMap(headerList []interface{}) map[interface{}]interface{} {
refom?

2023-08-24 18:21 UTC, serprex commented on pkg/storages/s3/session.go
> +func refomHeaderListToMap(headerList []interface{}) map[interface{}]interface{} {
```suggestion
func refomHeaderListToMap(headerList []interface{}) map[string]string {
```
Might as well put the types as strings if only use is going to be casting all to string

2023-08-25 11:00 UTC, x4m approved these changes

2023-08-25 11:00 UTC, merged