Retry fetch file
wal-g/wal-g pull request #1608
Opened 2023-12-13 14:01 UTC by debebantur

Now file retries are not controlled by user.  Seems it is better to set it in config

2023-12-15 08:39 UTC, EinKrebs requested changes

2023-12-15 08:39 UTC, EinKrebs commented on docs/Greenplum.md
> +WALG_DOWNLOAD_FILE_RETRIES: 10
```suggestion
WALG_DOWNLOAD_FILE_RETRIES: 15
```

2023-12-15 08:39 UTC, EinKrebs commented on internal/extract_test.go
> +	assert.Less(t, duration, time.Second*4)
Better use something different here

2023-12-15 09:38 UTC, debebantur commented on internal/extract_test.go
> +	assert.Less(t, duration, time.Second*4)
Changed it to checking logger

2023-12-19 11:23 UTC, EinKrebs approved these changes

2023-12-19 11:23 UTC, merged