Update mongodb documentation
wal-g/wal-g pull request #794
Opened 2020-10-28 13:28 UTC by perekalov

2020-10-28 13:56 UTC, kuzpactor requested changes

2020-10-28 13:56 UTC, kuzpactor commented on MongoDB.md
> +**Interface of MongoDB features now is unstable**
`is currently unstable`.
"Now" here reads as "becomes"

2020-10-28 13:56 UTC, kuzpactor commented on MongoDB.md
> +Defines longest point-int-time recovery period for `oplog-purge`.
`point-in-time`

2020-10-28 13:56 UTC, kuzpactor commented on MongoDB.md
> +* ##### `OPLOG_PITR_DISCOVERY_INTERVAL`
Perhaps, a more in-depth description of this option may be necessary.
May be I miss something, but I did not get the meaning of this key.

2020-10-28 13:56 UTC, kuzpactor commented on MongoDB.md
> +Note: archiving works only on primary, but you can run it on all replicaset nodes with config option `OPLOG_PUSH_WAIT_FOR_BECOME_PRIMARY: true`.
`... on any replicaset node using config ...`

2020-10-28 13:56 UTC, kuzpactor commented on MongoDB.md
> +You may add ```--drop``` option to restore command, but do it with caution.
A reminder of what `--drop` actually does would be nice here.

```
You may also add --drop option to restore command. This option will delete local files (?) and thus extra care should be exercised.
```

2020-10-28 13:56 UTC, kuzpactor commented on MongoDB.md
> +# Enable archiving statistics collection
Perhaps a more unambiguous --
`Collect statistics on archiving process`.

2020-10-30 10:19 UTC, VGoshev approved these changes

2020-10-30 10:19 UTC, merged