unit tests for cleaner Kolpakov Vladimir
wal-g/wal-g pull request #911
Opened 2021-03-24 17:41 UTC by Xaspy

@usernamedt

2021-03-25 01:59 UTC, Xaspy commented on internal/cleaner.go
>  	if err != nil {
кажется, что стоит return делать, если при полуении файлов произошла ошибка. по идее конечно мы вряд ли получим файлы, если получили не нулевую ошибку, но всё же не думаю, что можно быть на 100% уверенным в том, что возвращает другой не протестированный метод

2021-03-25 02:03 UTC, Xaspy commented on internal/cleaner.go
>  	if err != nil {
а хотя я сейчас глянул место, где может быть получена ошибка, там nil возвращается, если ошибка не нулевая, но всё же я б подумал насчет return'а, вдруг мы GetFiles изменим в будущем :)

2021-03-29 09:15 UTC, usernamedt commented on internal/cleaner.go
>  	if err != nil {
ок, думаю стоит запилить отдельным pr :)

2021-03-29 09:18 UTC, usernamedt commented on internal/cleaner.go
>  	if err != nil {
Я думаю что стоит проверить, что не только ненужные файлы удаляются, но что и остаются нужные.

2021-03-29 09:19 UTC, usernamedt commented on internal/prefetch_test.go
> -	assert.NotContains(t, cleaner.deleted, "/A/.wal-g/prefetch/000000010000000100000058")
Кажется, что этот тест можно сохранить в cleaner_test?

2021-03-29 14:18 UTC, usernamedt requested changes
needs changes

2021-03-29 14:26 UTC, Xaspy commented on internal/prefetch_test.go
> -	assert.NotContains(t, cleaner.deleted, "/A/.wal-g/prefetch/000000010000000100000058")
TestCleanupSimpleFiles - это он же, только с другим именем, но без проверки того, что он не удаляет того, что не нужно удалять. замечание принял, поправлю все тесты, добавив проверку на то, не удаляются ли те файлы, которые удалять не нужно

2021-03-29 15:48 UTC, usernamedt approved these changes

2021-03-29 15:49 UTC, usernamedt commented
lgtm

2021-03-29 15:49 UTC, merged