[redis-binary] add more info for 'backup-list' command
wal-g/wal-g pull request #968
Opened 2021-05-08 00:19 UTC by proggga

redis "backup-list" worked by default

so I've complete '--detail' param, now it works like says in README.md:
supports: --detail , --json , --pretty

2021-05-08 16:07 UTC, perekalov requested changes
It would be helpful to see output examples here.

2021-05-08 21:06 UTC, proggga commented
```
>  ./main/redis/wal-g backup-list --walg-file-prefix tmp --detail --json --pretty
[
    {
        "BackupName": "stream_20210507T224528Z",
        "StartLocalTime": "2021-05-08T01:45:28.96482+03:00",
        "FinishLocalTime": "2021-05-08T01:45:29.113551+03:00",
        "UserData": {
            "shard": "debug_redis"
        },
        "Permanent": true,
        "DataSize": 337987,
        "BackupSize": 149122
    },
    {
        "BackupName": "stream_20210507T224531Z",
        "StartLocalTime": "2021-05-08T01:45:31.354951+03:00",
        "FinishLocalTime": "2021-05-08T01:45:31.465384+03:00",
        "UserData": {
            "shard": "debug_redis"
        },
        "Permanent": true,
        "DataSize": 337987,
        "BackupSize": 149122
    }
]

 ./main/redis/wal-g backup-list --walg-file-prefix tmp --detail --pretty
+---+-------------------------+----------------------------------+----------------------------------+------------------------+-----------+-------------+-----------+
| # | NAME                    | START TIME                       | FINISH TIME                      | USERDATA               | DATA SIZE | BACKUP SIZE | PERMANENT |
+---+-------------------------+----------------------------------+----------------------------------+------------------------+-----------+-------------+-----------+
| 1 | stream_20210507T224528Z | Saturday, 08-May-21 01:45:28 MSK | Saturday, 08-May-21 01:45:29 MSK | map[shard:debug_redis] |    337987 |      149122 | true      |
| 2 | stream_20210507T224531Z | Saturday, 08-May-21 01:45:31 MSK | Saturday, 08-May-21 01:45:31 MSK | map[shard:debug_redis] |    337987 |      149122 | true      |
+---+-------------------------+----------------------------------+----------------------------------+------------------------+-----------+-------------+-----------+

./main/redis/wal-g backup-list --walg-file-prefix tmp --detail
name                    start_time                finish_time               user_data              data_size backup_size permanent
stream_20210507T224528Z 2021-05-08T01:45:28+03:00 2021-05-08T01:45:29+03:00 map[shard:debug_redis] 337987    149122      true
stream_20210507T224531Z 2021-05-08T01:45:31+03:00 2021-05-08T01:45:31+03:00 map[shard:debug_redis] 337987    149122      true

./main/redis/wal-g backup-list --walg-file-prefix tmp 
name                    last_modified             wal_segment_backup_start
stream_20210507T224528Z 2021-05-08T01:45:29+03:00 ZZZZZZZZZZZZZZZZZZZZZZZZ
stream_20210507T224531Z 2021-05-08T01:45:31+03:00 ZZZZZZZZZZZZZZZZZZZZZZZZ
```

2021-05-08 21:08 UTC, proggga commented on internal/databases/redis/backup_list_handler.go
> +		writer.AppendRow(table.Row{idx + 1, b.BackupName, b.StartLocalTime.Format(time.RFC850), b.FinishLocalTime.Format(time.RFC850), b.UserData, b.DataSize, b.BackupSize, b.DataSize / 1024 / 1024, b.Back
Fixed - removed this columns

2021-05-10 11:35 UTC, perekalov approved these changes

2021-05-10 11:35 UTC, merged