[WIP] Greenplum backup push
wal-g/wal-g pull request #992
Opened 2021-05-27 09:52 UTC by nastprol

2021-06-07 13:15 UTC, usernamedt commented
Hi!
I am having trouble running `backup-push` on Greenplum 6.15:
```
WARNING: 2021/06/07 15:53:56.745012 Couldn't get system identifier because of error: 'System Identifier: getting identifier of DB failed: ERROR: function pg_control_system() does not exist (SQLSTATE 42883)'
INFO: 2021/06/07 15:53:56.749770 Running wal-g on segments
panic: 20210607:15:53:56 wal-g:root:xxxxx:079003-[CRITICAL]:-Unable to run wal-g on 5 segments. See /root/gpAdminLogs/wal-g_20210607.log for a complete list of errors.

goroutine 1 [running]:
github.com/greenplum-db/gp-common-go-libs/gplog.abort(0xc000a7f950, 0x1, 0x1)
	/home/usernamedt/gp_walg/wal-g/vendor/github.com/greenplum-db/gp-common-go-libs/gplog/gplog.go:353 +0x105
github.com/greenplum-db/gp-common-go-libs/gplog.Fatal(0x1d54d00, 0xc0001a2d00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/usernamedt/gp_walg/wal-g/vendor/github.com/greenplum-db/gp-common-go-libs/gplog/gplog.go:303 +0x465
github.com/greenplum-db/gp-common-go-libs/cluster.LogFatalClusterError(0xc0001ae320, 0x16, 0xc000a7fa02, 0x5)
	/home/usernamedt/gp_walg/wal-g/vendor/github.com/greenplum-db/gp-common-go-libs/cluster/cluster.go:398 +0x21a
github.com/greenplum-db/gp-common-go-libs/cluster.(*Cluster).CheckClusterError(0xc0003fba40, 0xc000690580, 0x1b1e7be, 0x13, 0x17717a0, 0x1b73a28, 0x0, 0x0, 0x0)
	/home/usernamedt/gp_walg/wal-g/vendor/github.com/greenplum-db/gp-common-go-libs/cluster/cluster.go:380 +0x565
github.com/wal-g/wal-g/internal/databases/greenplum.(*BackupHandler).HandleBackupPush(0xc0003f8480)
	/home/usernamedt/gp_walg/wal-g/internal/databases/greenplum/backup_push_handler.go:103 +0x24f
github.com/wal-g/wal-g/cmd/gp.glob..func1(0x2ced800, 0xc00000fe60, 0x0, 0x2)
	/home/usernamedt/gp_walg/wal-g/cmd/gp/backup_push.go:66 +0x225
github.com/spf13/cobra.(*Command).execute(0x2ced800, 0xc00000fde0, 0x2, 0x2, 0x2ced800, 0xc00000fde0)
	/home/usernamedt/gp_walg/wal-g/vendor/github.com/spf13/cobra/command.go:830 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2ceda80, 0x45302a, 0x2d065e0, 0xc000000180)
	/home/usernamedt/gp_walg/wal-g/vendor/github.com/spf13/cobra/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	/home/usernamedt/gp_walg/wal-g/vendor/github.com/spf13/cobra/command.go:864
github.com/wal-g/wal-g/cmd/gp.Execute()
	/home/usernamedt/gp_walg/wal-g/cmd/gp/gp.go:33 +0x31
main.main()
	/home/usernamedt/gp_walg/wal-g/main/gp/main.go:8 +0x25
```

It would be cool to create some basic docker test to make sure that WAL-G can create a backup without errors.

2021-06-13 17:34 UTC, nastprol commented
> Hi!
> I am having trouble running `backup-push` on Greenplum 6.15:
> 
> ```
> WARNING: 2021/06/07 15:53:56.745012 Couldn't get system identifier because of error: 'System Identifier: getting identifier of DB failed: ERROR: function pg_control_system() does not exist (SQLSTATE 42883)'
> INFO: 2021/06/07 15:53:56.749770 Running wal-g on segments
> panic: 20210607:15:53:56 wal-g:root:xxxxx:079003-[CRITICAL]:-Unable to run wal-g on 5 segments. See /root/gpAdminLogs/wal-g_20210607.log for a complete list of errors.
> 
> goroutine 1 [running]:
> github.com/greenplum-db/gp-common-go-libs/gplog.abort(0xc000a7f950, 0x1, 0x1)
> 	/home/usernamedt/gp_walg/wal-g/vendor/github.com/greenplum-db/gp-common-go-libs/gplog/gplog.go:353 +0x105
> github.com/greenplum-db/gp-common-go-libs/gplog.Fatal(0x1d54d00, 0xc0001a2d00, 0x0, 0x0, 0x0, 0x0, 0x0)
> 	/home/usernamedt/gp_walg/wal-g/vendor/github.com/greenplum-db/gp-common-go-libs/gplog/gplog.go:303 +0x465
> github.com/greenplum-db/gp-common-go-libs/cluster.LogFatalClusterError(0xc0001ae320, 0x16, 0xc000a7fa02, 0x5)
> 	/home/usernamedt/gp_walg/wal-g/vendor/github.com/greenplum-db/gp-common-go-libs/cluster/cluster.go:398 +0x21a
> github.com/greenplum-db/gp-common-go-libs/cluster.(*Cluster).CheckClusterError(0xc0003fba40, 0xc000690580, 0x1b1e7be, 0x13, 0x17717a0, 0x1b73a28, 0x0, 0x0, 0x0)
> 	/home/usernamedt/gp_walg/wal-g/vendor/github.com/greenplum-db/gp-common-go-libs/cluster/cluster.go:380 +0x565
> github.com/wal-g/wal-g/internal/databases/greenplum.(*BackupHandler).HandleBackupPush(0xc0003f8480)
> 	/home/usernamedt/gp_walg/wal-g/internal/databases/greenplum/backup_push_handler.go:103 +0x24f
> github.com/wal-g/wal-g/cmd/gp.glob..func1(0x2ced800, 0xc00000fe60, 0x0, 0x2)
> 	/home/usernamedt/gp_walg/wal-g/cmd/gp/backup_push.go:66 +0x225
> github.com/spf13/cobra.(*Command).execute(0x2ced800, 0xc00000fde0, 0x2, 0x2, 0x2ced800, 0xc00000fde0)
> 	/home/usernamedt/gp_walg/wal-g/vendor/github.com/spf13/cobra/command.go:830 +0x2c2
> github.com/spf13/cobra.(*Command).ExecuteC(0x2ceda80, 0x45302a, 0x2d065e0, 0xc000000180)
> 	/home/usernamedt/gp_walg/wal-g/vendor/github.com/spf13/cobra/command.go:914 +0x30b
> github.com/spf13/cobra.(*Command).Execute(...)
> 	/home/usernamedt/gp_walg/wal-g/vendor/github.com/spf13/cobra/command.go:864
> github.com/wal-g/wal-g/cmd/gp.Execute()
> 	/home/usernamedt/gp_walg/wal-g/cmd/gp/gp.go:33 +0x31
> main.main()
> 	/home/usernamedt/gp_walg/wal-g/main/gp/main.go:8 +0x25
> ```
> 
> It would be cool to create some basic docker test to make sure that WAL-G can create a backup without errors.

Hi!
I added the test as you requested. You can run `make gp_test`

2021-06-14 09:33 UTC, usernamedt commented
> Hi!
> I added the test as you requested. You can run `make gp_test`

This needs to be included into the [CI workflow](https://github.com/wal-g/wal-g/blob/490b27137551f1dbccac4a61ffe27f728e976ad4/.github/workflows/dockertests.yml#L73).

2021-06-18 09:52 UTC, usernamedt requested changes
need a couple of fixes before merging

2021-06-18 09:52 UTC, usernamedt commented on internal/databases/postgres/connect.go
> +		config.RuntimeParams["gp_role"] = "utility"
I think it is OK to leave this hinge at the MVP stage, but I suggest extracting this logic to the explicit function to make it clear what is going on. For example, you may name it `tryConnectToGpSegment` or something like that. And leave some comment regarding this logic.

2021-06-18 09:52 UTC, usernamedt commented on internal/databases/postgres/queryRunner.go
> +func (queryRunner *PgQueryRunner) buildCreateGreenplumRestorePoint(restorePointName string) string {
Better move the Greenplum-specific functions to the separate query runner.
You can introduce the GpQueryRunner and embed the existing PgQueryRunner into it.

2021-06-18 09:52 UTC, usernamedt commented on internal/databases/postgres/timeline.go
>  		return 0, newIncorrectBackupNameError(backupName)
Add a couple of unit tests for new functionality regarding the possible backup name prefix.

2021-06-30 09:26 UTC, usernamedt requested changes

2021-06-30 09:26 UTC, usernamedt commented on docker/pg_tests/scripts/tests/backup_add_name_prefix_test.sh
> +wal-g --config=${TMP_CONFIG} backup-list
So, as I understood, the logic is to check the name of the resulting backup after calling the backup-list? If so, I guess this test lacks a couple of ending lines :)

2021-06-30 09:26 UTC, usernamedt commented on internal/databases/greenplum/queryRunner.go
> +func NewPgQueryRunner(conn *pgx.Conn) (*GpQueryRunner, error) {
`NewGpQueryRunner`

2021-07-05 19:00 UTC, usernamedt approved these changes

2021-07-06 06:32 UTC, merged